// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITGfX3GOVGY7nU07_Vsmyr8cBzv7uaMM',
    appId: '1:255696252779:web:e11b5f88ee9e759600262e',
    messagingSenderId: '255696252779',
    projectId: 'fir-authentification-9cbaa',
    authDomain: 'fir-authentification-9cbaa.firebaseapp.com',
    storageBucket: 'fir-authentification-9cbaa.appspot.com',
    measurementId: 'G-SHWQSDMNEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnOcpQsA0sjOEN34csJuUW32fSw3EAN4',
    appId: '1:255696252779:android:0b7dcbb8a04cb80d00262e',
    messagingSenderId: '255696252779',
    projectId: 'fir-authentification-9cbaa',
    storageBucket: 'fir-authentification-9cbaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe3o9o6pkNlfBeXsUKBdXFcXOxK_pgPDI',
    appId: '1:255696252779:ios:b73f2b1e3e25423000262e',
    messagingSenderId: '255696252779',
    projectId: 'fir-authentification-9cbaa',
    storageBucket: 'fir-authentification-9cbaa.appspot.com',
    iosBundleId: 'com.example.hwFirebaseAuthentification',
  );
}
